### PR TITLE
Add Russian support.

### PR DESCRIPTION
**Pull request by geniuspopeye**
Add Russian support.
image

### CODE REVIEW

**Comment by alex-praschek** [comment]
@geniuspopeye Thank you for your contribution! Could you merge develop into this branch first, please? I'll accept the PR afterwards :)

**Comment by geniuspopeye** [comment]
@alex-praschek Which branch do you mean?

**Comment by geniuspopeye** [comment]
And I have another question for you, do you know how to translate this panel (in pic)?
image

**Comment by alex-praschek** [comment]
@geniuspopeye Please merge the develop branch into your branch. I can't merge this PR otherwise. 

No, unfortunately I don't. I'm afraid this is not possible at all. 
@dominikhorn93 Do you know if this is possible?

**Comment by geniuspopeye** [comment]
@alex-praschek I seem to have resolved the conflict, but I don’t know why it can’t merge. I have one bad idea, it's to delete my fork and create a new one and put my changes there.

**Comment by alex-praschek** [comment]
@geniuspopeye Unfortunately I can't merge for you, since the repository is not ours. Just try to resolve the conflicts again. You don't need to merge the files in the dist folder. You can just override them with a new build after you have merged the other files. If you need further assistance with that, just tell me. :)

**Pull request merged**
